// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebcrcsiepxuowptxkwmd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImViY3Jjc2llcHh1b3dwdHhrd21kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNjQ4MjEsImV4cCI6MjA2NTk0MDgyMX0.pydjUXA9bKsVb0sPO26oZw_Rub-olu8-VeSJD8fTQ28";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);